# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core

import flatbuffers

class PointCloudR(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPointCloudR(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PointCloudR()
        x.Init(buf, n + offset)
        return x

    # PointCloudR
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PointCloudR
    def Points(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # PointCloudR
    def PointsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # PointCloudR
    def PointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def PointCloudRStart(builder): builder.StartObject(1)
def PointCloudRAddPoints(builder, points): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0)
def PointCloudRStartPointsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PointCloudREnd(builder): return builder.EndObject()
